name: Run Pyright

on:
  pull_request:
    branches: [ main ]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install your project dependencies
          python -m pip install -e project/nanoeval
          python -m pip install -e project/alcatraz
          pip install pyright

      - name: Run pyright
        run: pyright
