name: Run Pytest

on:
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install packages
        run: |
          python -m pip install -e project/nanoeval
          python -m pip install -e project/alcatraz
          python -m pip install pytest

      - name: Run tests
        run: |
          pytest